version: 1
updates:
  - package-ecosystem: "Cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
