[package]
name = "exilvmlinuz"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
gravatar-rs = "0.2.2"
bounce = { version ="0.7.0", features = ["helmet"] }