[package]
name = "exilvmlinuz"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
gravatar-rs = "0.2.3"
bounce = { version ="0.9.0", features = ["helmet"] }