name: Build and deploy to Github Pages

# only run on changes to master
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Install Trunk
      run: cargo install trunk
    - name: Add the WASM build target
      run: rustup target add wasm32-unknown-unknown
    - name: Build the app
      run: trunk build --release --public-url ${{ github.event.repository.name }}
    - name: Upload `dist` directory as an artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
